id: P009263
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:35.520063
source_metadata:
  id: bdr:W1KG25122
  title: རྒྱལ་སྲས་ལག་ལེན་རྩ་འགྲེལ་གཅེས་བསྡུས།
  author: ''
  volumes:
    9abe84ac148546a78a73bb00ded4b59c:
      image_group_id: I1KG25124
      title: ''
      volume_number: 1
      total_pages: 360
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
