id: IA8B847F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:05:14+00:00'
last_modified: '2022-06-08T09:46:42.439788+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25122
  title: རྒྱལ་སྲས་ལག་ལེན་རྩ་འགྲེལ་གཅེས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8299':
      image_group_id: I1KG25124
      title: ''
      total_pages: 360
      order: 1
      base_file: 8299.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
